#!/bin/bash
# Tradução de comandos Linux
alias limpar='clear'
alias atualizar='sudo apt update && sudo apt upgrade'
alias instalar='sudo apt install'
alias remover='sudo apt remove'
alias procurar='apt search'
alias pc-info='neofetch'
alias ondeestou='pwd'
alias ajuda='cat ~/comandos-pt/ajuda.txt'
alias baixar='sudo apt install'
alias desinstalar='sudo apt remove'
alias ver-ip='hostname -I'
alias desligar='sudo shutdown now'
alias reiniciar='sudo reboot'
